image: atlassian/default-image:3
clone:
  depth: full

pipelines:
  branches:
    main:
#      - step:
#          name: Deploy to Production
#          deployment: Production
#          script:
#            - docker build --build-arg REACT_APP_BASE_URL=$REACT_APP_BASE_URL -t quizyeasy-ui .
#            - echo ${DOCKER_PASSWORD} | docker login --username "$DOCKER_USERNAME" --password-stdin
#            - docker push charkasau/quizyeasy-ui
#          services:
#            - docker
      - step:
          name: deploy
          script:
             - echo 'Hi'
#            - apk update; apk add curl
#            - curl -L https://fly.io/install.sh | sh
#            - export FLYCTL_INSTALL="/root/.fly"
#            - export PATH="$FLYCTL_INSTALL/bin:$PATH"
#             #Аутентификация для доступа к fly.io секретам
#            - echo $FLY_API_TOKEN > /root/.fly/api_token
#            - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#            - flyctl deploy
