image: docker
clone:
  depth: full

pipelines:
  branches:
    main:
    - step:
        name: deploy
        script:
          - apt-get -y update; apt-get -y install curl
          - apt-get -y update; apt-get -y install docker
          - curl -L https://fly.io/install.sh | sh
          - export FLYCTL_INSTALL="/root/.fly"
          - export PATH="$FLYCTL_INSTALL/bin:$PATH"
          # Аутентификация для доступа к fly.io секретам
          - echo $FLY_API_TOKEN > /root/.fly/api_token
          # Извлечение URL backend'a
          - REACT_APP_BASE_URL=$(flyctl secrets get REACT_APP_BASE_URL)
          # Передаем URL backend'a как аргумент сборки к Docker
          - docker build --build-arg REACT_APP_BASE_URL=$REACT_APP_BASE_URL -t quizyeasy-ui .
          # Пушим образ в Docker Hub
          - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          - docker push charkasau/quizyeasy-ui
          - flyctl deploy
