app = "quizyeasy-ui"
primary_region = "waw"

[build]
  image = "your-dockerhub-username/your-image-name:tag"
[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[args]]
    name = "REACT_APP_BASE_URL"
    value = "http://quizyeasy-api.internal/api/v1"
