app = "quizyeasy-ui"
primary_region = "waw"

[build]
[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]
